### PR TITLE
Fix corrupted image

### PR DESCRIPTION
**Pull request by APdev93**

### CODE REVIEW

**Comment by mayank0274** [comment]
have you tested it ? its giving "Failed to fetch" error

**Comment by APdev93** [comment]
> have you tested it ? its giving "Failed to fetch" error
Is it true that it raises an error?

**Comment by APdev93** [comment]
What's the error like?

**Comment by mayank0274** [comment]
see these images , i think request to system file url is not resolving, it remains in pending state:-
https://ibb.co/M7YTSDZ
https://ibb.co/dBj1yKx

it works on your device?

**Comment by APdev93** [comment]
> see these images , i think request to system file url is not resolving, it remains in pending state:- https://ibb.co/M7YTSDZ https://ibb.co/dBj1yKx
> 
> it works on your device?

I usually use domtoimage like that and there are no errors, but I have never tried making a plugin, and when I tried this plugin to test, an error appeared.
Screenshot_20231227-131523~2

**Pull request closed without merging**
